### ISSUE TITLE
Get user status (i guess?)

### ISSUE THREAD

**Issue by editid0** [KILR007/roblox.py#1]
An option to get the text under the name 
image:

![image](https://user-images.githubusercontent.com/66117959/104126679-ce18f600-5355-11eb-9bd0-371760bd9fc9.png)

**Comment by KILR007** [comment]
Alright sure will do it

**Comment by KILR007** [comment]
Done @editid0 
https://github.com/KILR007/roblox.py/blob/master/roblox_py/PlayerInfo.py#L458
