### ISSUE TITLE
roblox_py.Auth_Group.change_shout will fail with every other attempt

### ISSUE THREAD

**Issue by GammaWhiskey** [KILR007/roblox.py#18]
When posting several group shouts consecutively with `Auth_Group.change_shout`, the first time will succeed, the second time will throw an `AttributeError`, the third time will succeed, the fourth time will throw an `AttributeError`, and so on and so forth.

Example traceback: https://pastebin.com/2B0jcMGS

**Comment by KILR007** [comment]
Fixed in this [commit](https://github.com/KILR007/roblox.py/commit/6620960d8d0198906d27f4738ce5fdd13922ef4d) 👍🏻
