### ISSUE TITLE
Use Single  aiohttp ClientSession

### ISSUE THREAD

**Issue by KILR007** [KILR007/roblox.py#19]
As of now, roblox.py uses multiple ClientSession for making its request, this is however a bad practice as specified in the docs.

This decreases speed by a large potion

**Solution**
Make it use a single Session

**Current Solution**
*None*

**Comment by Anonymous136** [comment]
for a solution, you prob could do smth like `session = aiohttp.ClientSession()`

**Comment by Anonymous136** [comment]
oh wait no that doesnt work
