### ISSUE TITLE
client.get_user_info() should also be supported for usernames

### ISSUE THREAD

**Issue by Realcodoudou** [KILR007/roblox.py#5]
Title is self-explanatory. And it is possible to make since https://users.roblox.com/v1/usernames/users exists.

**Comment by KILR007** [comment]
That's not quite possible since,
Username **can** be numbers (ie -
[Profile link ](https://www.roblox.com/users/27151306/profile)

**Comment by KILR007** [comment]
That's why there is a other method for it
`client.get_user_by_name()` which returns PlayerInfo class (same as what `client.get_user_info()` returns )
