### ISSUE TITLE
 A way to use `client.get_place_by_id()` without authentication

### ISSUE THREAD

**Issue by Realcodoudou** [KILR007/roblox.py#6]

**Comment by GreenDiscord** [comment]
Hey! So do you have any cookies defined?
If not there's your issue, for stats like these you **need** cookies!

**Comment by KILR007** [comment]
> Hey! So do you have any cookies defined?
> If not there's your issue, for stats like these you **need** cookies!
> 
> 

Cookies are not really necessary u can use `client
get_asset()` method too for getting place info  tho

**Comment by KILR007** [comment]
Also, Don't close this issue, since
`client.get_asset()` don't have a method to get asset/place universe. So I need to implement a method to get it in the future
