### ISSUE TITLE
Add __repr__ methods

### ISSUE THREAD

**Issue by token631** [KILR007/roblox.py#8]
Add __repr__ methods to every ROBLOX model.

```
def __repr__(self):
 rep = self.name
 return rep
```
something like this

**Comment by KILR007** [comment]
Fixed in the commit [Commit](https://github.com/KILR007/roblox.py/commit/a6a7782878e68c3dd0cad64d6daa1270fac5018e)

**Comment by KILR007** [comment]
Fixed in this [Commit](https://github.com/KILR007/roblox.py/commit/a6a7782878e68c3dd0cad64d6daa1270fac5018e)
